In [1]:
%env KERAS_BACKEND=tensorflow

env: KERAS_BACKEND=tensorflow


In [2]:
%matplotlib inline

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
X_train_data = pd.read_csv('C:/Users/Chun/Desktop/PythonHW/train_test_data/X_train.csv')
Y_train_data = pd.read_csv('C:/Users/Chun/Desktop/PythonHW/train_test_data/Y_train.csv')
X_test_data = pd.read_csv('C:/Users/Chun/Desktop/PythonHW/train_test_data/X_test.csv')
Y_test_data = pd.read_csv('C:/Users/Chun/Desktop/PythonHW/train_test_data/Y_test.csv')

In [4]:
X_train0 = X_train_data.drop('0', axis=1)
X_trainRNN = X_train0.drop('1', axis=1)
X_test0 = X_test_data.drop('0', axis=1)
X_testRNN = X_test0.drop('1', axis=1)

In [5]:
Y_train = Y_train_data.drop('Unnamed: 0', axis=1)
Y_test = Y_test_data

In [6]:
x_trainRNN = X_trainRNN.values
x_testRNN = X_testRNN.values
y_train = Y_train.values
y_test = Y_test.values

In [7]:
x_trainRNN = np.reshape(x_trainRNN, (x_trainRNN.shape[0], 1, x_trainRNN.shape[1]))
x_testRNN = np.reshape(x_testRNN, (x_testRNN.shape[0], 1, x_testRNN.shape[1]))

In [8]:
from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense,Activation,Embedding, LSTM, Dropout
from keras.optimizers import SGD, Adam
from keras.utils import np_utils

C:\Users\Chun\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


## 模型一、有使用active function的LSTM後續混合NN

In [48]:
K=10 #LSTM的個數

In [49]:
modelRNN0 = Sequential()

In [50]:
modelRNN0.add(LSTM(K,input_dim=31))
modelRNN0.add(Dense(1, activation='sigmoid'))
modelRNN0.compile(loss='mse', optimizer='adam', metrics=['accuracy'])
modelRNN0.summary()

C:\Users\Chun\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
  """Entry point for launching an IPython kernel.
C:\Users\Chun\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(10, input_shape=(None, 31))`
  """Entry point for launching an IPython kernel.


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_4 (LSTM)                (None, 10)                1680      
_________________________________________________________________
dense_15 (Dense)             (None, 1)                 11        
Total params: 1,691
Trainable params: 1,691
Non-trainable params: 0
_________________________________________________________________


In [51]:
#訓練部分一(LSTM)
modelRNN0.fit(x_trainRNN, y_train, batch_size=1000, epochs=2)

Epoch 1/2
13147844/13147844 [==============================] - 63s 5us/step - loss: 8.1999 - acc: 0.8714
Epoch 2/2
13147844/13147844 [==============================] - 69s 5us/step - loss: 8.1954 - acc: 0.8728


In [52]:
score0 = modelRNN0.evaluate(x_testRNN, y_test)
print("loss:", score0[0])
print("正確率:", score0[1])

848248/848248 [==============================] - 19s 22us/step
loss: 20.024274286887614
正確率: 0.9206682479652177


In [53]:
y_train_predict0 = modelRNN0.predict(x_trainRNN)
y_test_predict0 = modelRNN0.predict(x_testRNN)

In [54]:
X_trainNN0 = X_train_data.iloc[:,0:2]
X_trainNN0['y_train_predict'] = y_train_predict0
X_testNN0 = X_test_data.iloc[:,0:2]
X_testNN0['y_test_predict'] = y_test_predict0

C:\Users\Chun\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
C:\Users\Chun\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.


In [55]:
x_trainNN0 = X_trainNN0.values
x_testNN0 = X_testNN0.values

In [56]:
modelNN0 = Sequential()
modelNN0.add(Dense(10, input_dim=3))
modelNN0.add(Activation('relu'))
modelNN0.add(Dense(5))
modelNN0.add(Activation('relu'))
modelNN0.add(Dense(1))
modelNN0.add(Activation('softmax'))
modelNN0.compile(loss='mse', optimizer=Adam(), metrics=['accuracy'])
modelNN0.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_16 (Dense)             (None, 10)                40        
_________________________________________________________________
activation_4 (Activation)    (None, 10)                0         
_________________________________________________________________
dense_17 (Dense)             (None, 5)                 55        
_________________________________________________________________
activation_5 (Activation)    (None, 5)                 0         
_________________________________________________________________
dense_18 (Dense)             (None, 1)                 6         
_________________________________________________________________
activation_6 (Activation)    (None, 1)                 0         
Total params: 101
Trainable params: 101
Non-trainable params: 0
_________________________________________________________________


In [57]:
modelNN0.fit(x_trainNN0, y_train, batch_size=1000, epochs=2)

Epoch 1/2
13147844/13147844 [==============================] - 24s 2us/step - loss: 8.8959 - acc: 0.0742
Epoch 2/2
13147844/13147844 [==============================] - 21s 2us/step - loss: 8.8959 - acc: 0.0742


In [58]:
score0 = modelNN0.evaluate(x_testNN0, y_test)
print('loss:', score0[0])
print('正確率:', score0[1])

848248/848248 [==============================] - 12s 14us/step
loss: 20.81680829191463
正確率: 0.04890079316426328


In [59]:
y_predict0 = modelNN0.predict(x_testNN0)

In [60]:
y_predict0

array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]], dtype=float32)

In [61]:
y_predict0[101]

array([1.], dtype=float32)

### 準確率只有約4.9%，且預測出來的值皆相同

## 模型二、沿用模型一，但調大LSTM個數，並將LSTM及NN架構皆移除激活函數

In [62]:
K1=20 #LSTM的個數

In [63]:
modelRNN1 = Sequential()

In [64]:
modelRNN1.add(LSTM(K1,input_dim=31))
modelRNN1.add(Dense(1))
modelRNN1.compile(loss='mse', optimizer='adam', metrics=['accuracy'])
modelRNN1.summary()

C:\Users\Chun\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
  """Entry point for launching an IPython kernel.
C:\Users\Chun\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(20, input_shape=(None, 31))`
  """Entry point for launching an IPython kernel.


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_5 (LSTM)                (None, 20)                4160      
_________________________________________________________________
dense_19 (Dense)             (None, 1)                 21        
Total params: 4,181
Trainable params: 4,181
Non-trainable params: 0
_________________________________________________________________


In [65]:
modelRNN1.fit(x_trainRNN, y_train, batch_size=1000, epochs=2)

Epoch 1/2
13147844/13147844 [==============================] - 91s 7us/step - loss: 7.1458 - acc: 0.8544
Epoch 2/2
13147844/13147844 [==============================] - 88s 7us/step - loss: 6.4720 - acc: 0.8558


In [66]:
score1 = modelRNN1.evaluate(x_testRNN, y_test)
print("loss:", score1[0])
print("正確率:", score1[1])

848248/848248 [==============================] - 21s 25us/step
loss: 18.190703680353863
正確率: 0.9012317152530863


In [67]:
y_train_predict1 = modelRNN1.predict(x_trainRNN)
y_test_predict1 = modelRNN1.predict(x_testRNN)

In [68]:
X_trainNN1 = X_train_data.iloc[:,0:2]
X_trainNN1['y_train_predict'] = y_train_predict1
X_testNN1 = X_test_data.iloc[:,0:2]
X_testNN1['y_test_predict'] = y_test_predict1

C:\Users\Chun\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
C:\Users\Chun\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.


In [69]:
x_trainNN1 = X_trainNN1.values
x_testNN1 = X_testNN1.values

In [70]:
modelNN1 = Sequential()
modelNN1.add(Dense(10, input_dim=3))
modelNN1.add(Dense(5))
modelNN1.add(Dense(1))
modelNN1.compile(loss='mse', optimizer=Adam(), metrics=['accuracy'])
modelNN1.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_20 (Dense)             (None, 10)                40        
_________________________________________________________________
dense_21 (Dense)             (None, 5)                 55        
_________________________________________________________________
dense_22 (Dense)             (None, 1)                 6         
Total params: 101
Trainable params: 101
Non-trainable params: 0
_________________________________________________________________


In [71]:
modelNN1.fit(x_trainNN1, y_train, batch_size=1000, epochs=2)

Epoch 1/2
13147844/13147844 [==============================] - 29s 2us/step - loss: 124784.9098 - acc: 0.4555
Epoch 2/2
13147844/13147844 [==============================] - 24s 2us/step - loss: 14.0640 - acc: 0.3215


In [72]:
score1 = modelNN1.evaluate(x_testNN1, y_test)
print('loss:', score1[0])
print('正確率:', score1[1])

848248/848248 [==============================] - 13s 15us/step
loss: 46.02581158358539
正確率: 0.038049013967613246


In [73]:
y_predict1 = modelNN1.predict(x_testNN1)

In [74]:
y_predict1

array([[-0.34963456],
       [-0.5479194 ],
       [-0.7264238 ],
       ...,
       [-6.2638183 ],
       [-7.2304883 ],
       [-7.2383    ]], dtype=float32)

In [75]:
y_predict1[101]

array([5.9656224], dtype=float32)

### 準確率只有約3.9%

## 模型三、沿用模型二，但將optimizer 換為 SGD試試看

In [102]:
modelRNN2 = Sequential()

In [103]:
modelRNN2.add(LSTM(K,input_dim=31))
modelRNN2.add(Dense(1))
modelRNN2.compile(loss='mse', optimizer='SGD', metrics=['accuracy'])
modelRNN2.summary()

C:\Users\Chun\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
  """Entry point for launching an IPython kernel.
C:\Users\Chun\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(10, input_shape=(None, 31))`
  """Entry point for launching an IPython kernel.


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_8 (LSTM)                (None, 10)                1680      
_________________________________________________________________
dense_31 (Dense)             (None, 1)                 11        
Total params: 1,691
Trainable params: 1,691
Non-trainable params: 0
_________________________________________________________________


In [104]:
modelRNN2.fit(x_trainRNN, y_train, batch_size=1000, epochs=2)

Epoch 1/2
13147844/13147844 [==============================] - 71s 5us/step - loss: 7.4950 - acc: 0.8653
Epoch 2/2
13147844/13147844 [==============================] - 65s 5us/step - loss: 6.9642 - acc: 0.8654


In [105]:
score2 = modelRNN2.evaluate(x_testRNN, y_test)
print("loss:", score2[0])
print("正確率:", score2[1])

848248/848248 [==============================] - 21s 25us/step
loss: 18.67258674372793
正確率: 0.9135724457941545


In [106]:
y_train_predict2 = modelRNN2.predict(x_trainRNN)
y_test_predict2 = modelRNN2.predict(x_testRNN)

In [107]:
X_trainNN2 = X_train_data.iloc[:,0:2]
X_trainNN2['y_train_predict'] = y_train_predict2
X_testNN2 = X_test_data.iloc[:,0:2]
X_testNN2['y_test_predict'] = y_test_predict2

C:\Users\Chun\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
C:\Users\Chun\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.


In [108]:
x_trainNN2 = X_trainNN2.values
x_testNN2 = X_testNN2.values

In [109]:
modelNN2 = Sequential()
modelNN2.add(Dense(10, input_dim=3))
modelNN2.add(Dense(5))
modelNN2.add(Dense(1))
modelNN2.compile(loss='mse', optimizer=SGD(), metrics=['accuracy'])
modelNN2.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_32 (Dense)             (None, 10)                40        
_________________________________________________________________
dense_33 (Dense)             (None, 5)                 55        
_________________________________________________________________
dense_34 (Dense)             (None, 1)                 6         
Total params: 101
Trainable params: 101
Non-trainable params: 0
_________________________________________________________________


In [110]:
modelNN2.fit(x_trainNN2, y_train, batch_size=1000, epochs=2)

Epoch 1/2
13147844/13147844 [==============================] - 22s 2us/step - loss: nan - acc: 7.6058e-08
Epoch 2/2
13147844/13147844 [==============================] - 20s 2us/step - loss: nan - acc: 0.0000e+00


In [111]:
score2 = modelNN2.evaluate(x_testNN2, y_test)
print('loss:', score2[0])
print('正確率:', score2[1])

848248/848248 [==============================] - 12s 14us/step
loss: nan
正確率: 0.0


In [112]:
y_predict2 = modelNN2.predict(x_testNN2)

In [113]:
y_predict2

array([[nan],
       [nan],
       [nan],
       ...,
       [nan],
       [nan],
       [nan]], dtype=float32)

In [114]:
y_predict2[101]

array([nan], dtype=float32)

### 準確率0%